version: '3'
services:
    web:
        image: node:6
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - "./:/home/node/app:cached"
        ports:
            - "9001:9001"
        command: "npm start"
        restart: always
